### PR TITLE
dynamic module build fix

### PR DESCRIPTION
**Pull request by yanchenko-igor**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @yanchenko-igor,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by erankor** [comment]
Hi @yanchenko-igor, 

We are currently in the process of formalizing the project under the BSD open source license. Once that is complete, I will be able to merge your pull (the change looks good). 
But I will need your approval to consider your contribution as being made under BSD license.

Thanks,

Eran

**Comment by yanchenko-igor** [comment]
Hi @erankor 

I don't mind to give any permissions, I just don't want to sign the CLA where I need to provide my personal data, would my approval in comments work?

**Comment by erankor** [comment]
hi @yanchenko-igor, I checked with our legal team, unfortunately, we won't be able to merge this pull without a signed CLA or at least an email with your name and contact info. If the second option sounds ok to you, you can send it to me directly to eran dot kornblau at kaltura dot com. 
I can assure you that your personal data will only be saved for legal reference, we won't be sharing it with any third parties, nor would we send you any marketing material.

Thanks

Eran

**Comment by erankor** [comment]
Merged, thanks

**Pull request merged**
